### ISSUE TITLE
Video Failing to Initialize in Channels DVR

### ISSUE THREAD

**Issue by psperry** [jnewland/hlstube#32] opened 2022-04-07 13:19 UTC
As promised, here is the  log of the issue I am experiencing. It seemed to stop yesterday but now it is common again.  Maybe because I was messing with it more than usual yesterday. Anyway, the first two lines below seem to be where I get the failure. The second two are when I try again and it works.  Let me know if I can help further. Thanks!

`2022/04/06 17:58:44 https://www.youtube.com/watch?v=mhJRzQsLZGg 403
2022/04/06 17:58:44 forgot about https://www.youtube.com/watch?v=mhJRzQsLZGg
2022/04/06 17:59:01 &url.URL{Scheme:"", Opaque:"", User:(*url.Userinfo)(nil), Host:"", Path:"/_/https://www.youtube.com/watch", RawPath:"", ForceQuery:false, RawQuery:"v=mhJRzQsLZGg", Fragment:"", RawFragment:""}`

**Comment by jnewland** [comment] 2022-04-07 13:57
Right on, thanks for opening this @psperry! I'll try to reproduce here shortly.

**Comment by jnewland** [comment] 2022-04-07 17:39
Hey @psperry I added a few retry mechanisms that I think might help. Mind trying out the latest code using the `ghcr.io/jnewland/hlstube:main` Docker image? If that works for you I'll create a new release.

**Comment by psperry** [comment] 2022-04-07 18:04
Okay. I have it installed and all seems to be working as it should. It seems to fail at unpredictable intervals so I will keep an eye on it over the weekend and let you know how it goes. Thanks for your help!

**Comment by jnewland** [comment] 2022-04-08 13:49
I reproduced this behavior again this morning: after my stream disconnected overnight, the first attempt to tune was a failure, likely because the old expired url was cached. Gonna try a few things and will report back after a bit of testing.

**Comment by psperry** [comment] 2022-04-09 11:53
Watchtower pulled down a new version of `ghcr.io/jnewland/hlstube:main` last night. I trust this is a new version? Anyway, will let you know how it goes.

**Comment by jnewland** [comment] 2022-04-09 13:09
Yup, I made a few changes and am happy with how it's looking. I haven't been able to reproduce this following those changes yet. Thanks for reporting this and sharing the logs! Should be fixed in https://github.com/jnewland/hlstube/releases/tag/v0.0.6

**Closed by jnewland** 2022-04-09 13:09 UTC

**Comment by psperry** [comment] 2022-04-09 17:28
Shouldn't this release be tagged "latest" instead of "v0.0.6" so that those auto-updating get the latest version?

**Comment by jnewland** [comment] 2022-04-10 12:26
@psperry yep the latest release is always also tagged with `latest`!

https://github.com/jnewland/hlstube/pkgs/container/hlstube lists all the tags.

**Comment by psperry** [comment] 2022-04-10 12:28
Odd. When I pulled latest, it install 0.0.5

**Comment by psperry** [comment] 2022-04-11 13:34
Pulled "latest" again this morning and it installed the correct version.  Strange. Must be a github cashing thing.
